'use strict';
const mongoose = require('mongoose');

const toolMasterSchema = new mongoose.Schema({

  tool_code: {
    type:      String,
    required:  false,     // auto-generated by pre-save hook
    unique:    true,
    sparse:    true,
    trim:      true,
    uppercase: true,
    index:     true,
  },
  tool_name: {
    type:     String,
    required: true,
    trim:     true,
  },
  tool_type: {
    type: String,
    enum: [
      'Progressive Die', 'Blanking Die', 'Forming Die',
      'Piercing Punch',  'Bending Tool', 'Drawing Die',
      'Trimming Die',    'Compound Die', 'Fixture',
      'Jig',             'Gauge',        'Other',
    ],
    required: true,
  },
  description: { type: String, default: '' },

  compatible_machines: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Machine' }],

  produces_item_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Item', default: null },
  produces_part_no: { type: String, default: '' },

  max_shots:                  { type: Number, required: true, min: 1 },
  current_shots:              { type: Number, default: 0,  min: 0 },
  shots_at_last_maintenance:  { type: Number, default: 0 },
  maintenance_interval_shots: { type: Number, default: 0 },

  alert_threshold_percent: { type: Number, default: 90, min: 1, max: 100 },
  maintenance_alert:       { type: Boolean, default: false },
  replacement_alert:       { type: Boolean, default: false },

  tool_material:    { type: String, default: '' },
  tool_size:        { type: String, default: '' },
  tool_weight_kg:   { type: Number, default: 0  },
  drawing_no:       { type: String, default: '' },
  drawing_revision: { type: String, default: '0' },

  tool_cost:          { type: Number, default: 0 },
  cost_per_shot:      { type: Number, default: 0 },
  refurbishment_cost: { type: Number, default: 0 },

  manufactured_by: {
    type:    String,
    enum:    ['In-House', 'External Vendor'],
    default: 'In-House',
  },
  vendor_id:   { type: mongoose.Schema.Types.ObjectId, ref: 'Vendor', default: null },
  vendor_name: { type: String, default: '' },

  warehouse_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Warehouse', default: null },
  bin_location: { type: String, default: '' },

  status: {
    type:    String,
    enum:    ['Active', 'Under Maintenance', 'Scrapped', 'In Use', 'Retired'],
    default: 'Active',
    index:   true,
  },

  purchase_date:              { type: Date,   default: null },
  last_used:                  { type: Date,   default: null },
  last_maintenance_at:        { type: Date,   default: null },
  next_maintenance_due_shots: { type: Number, default: 0   },

  maintenance_log: [{
    date:           { type: Date,   default: Date.now },
    type:           { type: String, enum: ['Sharpening', 'Repair', 'Inspection', 'Replacement', 'Regrind'], required: true },
    shots_before:   { type: Number, default: 0 },
    shots_reset_to: { type: Number, default: 0 },
    cost:           { type: Number, default: 0 },
    performed_by:   { type: String, default: '' },
    remarks:        { type: String, default: '' },
  }],

  is_active:  { type: Boolean, default: true, index: true },
  created_by: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  updated_by: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },

}, {
  timestamps: true,
  toJSON:  { virtuals: true },
  toObject: { virtuals: true },
});

// ── Virtuals ──────────────────────────────────────────────────────────────────
toolMasterSchema.virtual('life_used_percent').get(function () {
  return this.max_shots > 0
    ? +((this.current_shots / this.max_shots) * 100).toFixed(1)
    : 0;
});

toolMasterSchema.virtual('shots_remaining').get(function () {
  return Math.max(0, this.max_shots - this.current_shots);
});

toolMasterSchema.virtual('shots_since_maintenance').get(function () {
  return this.current_shots - this.shots_at_last_maintenance;
});

toolMasterSchema.virtual('maintenance_due').get(function () {
  if (!this.maintenance_interval_shots) return false;
  return (this.current_shots - this.shots_at_last_maintenance) >= this.maintenance_interval_shots;
});

// ── Hook 1: Auto-generate tool_code (runs first, before validation) ───────────
toolMasterSchema.pre('save', async function (next) {
  if (this.tool_code) return next();
  if (!this.isNew)    return next();
  try {
    const Counter = mongoose.model('SalesOrderIdCounter');
    const counter = await Counter.findOneAndUpdate(
      { _id: 'tool-master' },
      { $inc: { seq: 1 } },
      { upsert: true, new: true }
    );
    this.tool_code = `TOOL-${String(counter.seq).padStart(4, '0')}`;
    return next();
  } catch (e) {
    return next(e);
  }
});

// ── Hook 2: Auto-compute cost_per_shot and next_maintenance_due_shots ─────────
toolMasterSchema.pre('save', function (next) {
  if (this.tool_cost && this.max_shots) {
    this.cost_per_shot = +(this.tool_cost / this.max_shots).toFixed(6);
  }
  if (this.maintenance_interval_shots && this.current_shots !== undefined) {
    this.next_maintenance_due_shots =
      this.shots_at_last_maintenance + this.maintenance_interval_shots;
  }
  next();
});

// ── Indexes ───────────────────────────────────────────────────────────────────
toolMasterSchema.index({ tool_type: 1, status: 1 });
toolMasterSchema.index({ current_shots: 1, max_shots: 1 });
toolMasterSchema.index({ produces_item_id: 1 });

const ToolMaster = mongoose.model('ToolMaster', toolMasterSchema);
module.exports = ToolMaster;