'use strict';
// ─────────────────────────────────────────────────────────────────────────────
// routes/CRM/phase12Routes.js
//
// Phase 12 — Invoice, Payment, Credit Note, GSTR, AR Aging
// All routes require authentication middleware (protect) passed from app.js.
// Role checks (Manager, Accounts) are noted in comments.
//
// PDF GENERATION: All PDFs are generated by the frontend.
// Backend returns structured JSON data including:
//   - Invoice data with HSN breakup, totals, GST details
//   - QR code data URL for e-Invoice
//   - Pre-computed amount in words
//   - All necessary fields for frontend to render professional invoices
// ─────────────────────────────────────────────────────────────────────────────

const express = require('express');                  
const router = express.Router();
const { protect } = require('../../middleware/authMiddleware');

const {
  // BE-012 — Invoice
  createInvoice,
  getInvoices,
  getInvoiceById,
  getInvoiceDataForPdf,
  submitIRN,
  cancelIRN,
  sendInvoice,
  confirmInvoice,   
  cancelInvoice,    

  // BE-013 — Payments
  createPaymentReceipt,
  getPaymentReceiptById,
  getPaymentReceipts,
  bouncePayment,
  logCollectionFollowUp,
  createCustomerAdvance,
  getCustomerAdvances,
  getCustomerAdvanceById,
  applyAdvanceToInvoice,
  getTdsReconciliation,

  // BE-014 — Credit Notes & GSTR
  createCreditNote,
  getCreditNotes,
  getCreditNoteById,
  getGstr1Data,
  getGstr3bData,
  getArAging,
  getMonthlyRevenue,
  closeSalesOrder,
} = require('../../controllers/CRM/invoiceController');

// All routes require authentication
router.use(protect);

// ─────────────────────────────────────────────────────────────────────────────
// ██  INVOICE ROUTES  (BE-012)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @swagger
 * /api/invoices:
 *   post:
 *     summary: Create a new GST-compliant sales invoice
 *     tags: ["Phase 12 — Invoice"]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - so_id
 *               - dc_ids
 *               - items
 *             properties:
 *               so_id:
 *                 type: string
 *                 description: Sales Order ObjectId
 *                 example: "665abc123def456789012345"
 *               dc_ids:
 *                 type: array
 *                 items:
 *                   type: string
 *                 description: Array of Delivery Challan ObjectIds
 *                 example: ["665abc123def456789012346", "665abc123def456789012347"]
 *               invoice_date:
 *                 type: string
 *                 format: date
 *                 description: Invoice date (defaults to today)
 *               invoice_type:
 *                 type: string
 *                 enum: ["Tax Invoice", "Bill of Supply", "Export Invoice"]
 *                 default: "Tax Invoice"
 *               items:
 *                 type: array
 *                 minItems: 1
 *                 items:
 *                   type: object
 *                   required:
 *                     - part_no
 *                     - hsn_code
 *                     - dispatched_qty
 *                     - unit_price
 *                   properties:
 *                     part_no:
 *                       type: string
 *                     part_name:
 *                       type: string
 *                     hsn_code:
 *                       type: string
 *                     unit:
 *                       type: string
 *                       enum: ["Nos", "Kg", "Meter", "Set", "Piece"]
 *                       default: "Nos"
 *                     dispatched_qty:
 *                       type: number
 *                       minimum: 0.001
 *                     unit_price:
 *                       type: number
 *                       minimum: 0
 *                     discount_percent:
 *                       type: number
 *                       default: 0
 *                     gst_percentage:
 *                       type: number
 *                       default: 18
 *               internal_remarks:
 *                 type: string
 *     responses:
 *       201:
 *         description: Invoice created successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 message:
 *                   type: string
 *                 data:
 *                   $ref: '#/components/schemas/Invoice'
 *       400:
 *         description: Validation error or missing required fields
 *       401:
 *         description: Unauthorized
 *       404:
 *         description: Sales Order or Customer not found
 */
router.post('/', createInvoice);

/**
 * @swagger
 * /api/invoices:
 *   get:
 *     summary: List invoices with filters and pagination
 *     tags: ["Phase 12 — Invoice"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: status
 *         schema:
 *           type: string
 *         description: Comma-separated statuses e.g. "Submitted,Sent"
 *       - in: query
 *         name: payment_status
 *         schema:
 *           type: string
 *           enum: ["Unpaid", "Partially Paid", "Fully Paid"]
 *       - in: query
 *         name: customer_id
 *         schema:
 *           type: string
 *       - in: query
 *         name: from
 *         schema:
 *           type: string
 *           format: date
 *       - in: query
 *         name: to
 *         schema:
 *           type: string
 *           format: date
 *       - in: query
 *         name: page
 *         schema:
 *           type: integer
 *           default: 1
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *           default: 20
 *     responses:
 *       200:
 *         description: Paginated invoice list
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 data:
 *                   type: array
 *                   items:
 *                     $ref: '#/components/schemas/InvoiceSummary'
 *                 pagination:
 *                   type: object
 *       401:
 *         description: Unauthorized
 */
router.get('/', getInvoices);

// ================================================================
// SPECIFIC ROUTES (NO :id PARAMETER) - MUST COME BEFORE PARAMETERIZED ROUTES
// ================================================================

/**
 * @swagger
 * /api/invoices/customer-advances:
 *   get:
 *     summary: List customer advances
 *     tags: ["Phase 12 — Advance"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: customer_id
 *         schema:
 *           type: string
 *       - in: query
 *         name: status
 *         schema:
 *           type: string
 *           enum: ["Open", "Partially Adjusted", "Fully Adjusted", "Refunded"]
 *       - in: query
 *         name: page
 *         schema:
 *           type: integer
 *           default: 1
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *           default: 20
 *     responses:
 *       200:
 *         description: List of customer advances
 */
router.get('/customer-advances', getCustomerAdvances);

/**
 * @swagger
 * /api/invoices/customer-advances:
 *   post:
 *     summary: Record customer advance payment (before invoice)
 *     tags: ["Phase 12 — Advance"]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - customer_id
 *               - total_amount
 *               - payment_mode
 *             properties:
 *               customer_id:
 *                 type: string
 *               advance_date:
 *                 type: string
 *                 format: date
 *               payment_mode:
 *                 type: string
 *                 enum: ["NEFT", "RTGS", "IMPS", "Cheque", "DD", "Cash", "UPI", "Bank Transfer"]
 *               total_amount:
 *                 type: number
 *                 minimum: 0.01
 *               instrument_no:
 *                 type: string
 *               instrument_date:
 *                 type: string
 *                 format: date
 *               bank_name:
 *                 type: string
 *               remarks:
 *                 type: string
 *     responses:
 *       201:
 *         description: Advance recorded successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 message:
 *                   type: string
 *                 data:
 *                   $ref: '#/components/schemas/CustomerAdvance'
 *       404:
 *         description: Customer not found
 */
router.post('/customer-advances', createCustomerAdvance);

/**
 * @swagger
 * /api/invoices/customer-advances/{id}:
 *   get:
 *     summary: Get customer advance details by ID
 *     tags: ["Phase 12 — Advance"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: CustomerAdvance ObjectId
 *     responses:
 *       200:
 *         description: Advance details with adjustment history
 *       404:
 *         description: Advance not found
 */
router.get('/customer-advances/:id', getCustomerAdvanceById);

/**
 * @swagger
 * /api/invoices/payment-receipts:
 *   get:
 *     summary: List payment receipts with filters
 *     tags: ["Phase 12 — Payment"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: customer_id
 *         schema:
 *           type: string
 *       - in: query
 *         name: status
 *         schema:
 *           type: string
 *           enum: ["Active", "Bounced", "Reversed"]
 *       - in: query
 *         name: from
 *         schema:
 *           type: string
 *           format: date
 *       - in: query
 *         name: to
 *         schema:
 *           type: string
 *           format: date
 *       - in: query
 *         name: page
 *         schema:
 *           type: integer
 *           default: 1
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *           default: 20
 *     responses:
 *       200:
 *         description: Paginated payment receipt list
 *       401:
 *         description: Unauthorized
 */
router.get('/payment-receipts', getPaymentReceipts);

/**
 * @swagger
 * /api/invoices/payment-receipts:
 *   post:
 *     summary: Create payment receipt with multi-invoice allocation and TDS
 *     tags: ["Phase 12 — Payment"]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - customer_id
 *               - total_amount
 *               - payment_mode
 *               - allocations
 *             properties:
 *               customer_id:
 *                 type: string
 *               receipt_date:
 *                 type: string
 *                 format: date
 *               payment_mode:
 *                 type: string
 *                 enum: ["NEFT", "RTGS", "IMPS", "Cheque", "DD", "Cash", "UPI", "Credit Card", "Bank Transfer"]
 *               total_amount:
 *                 type: number
 *                 minimum: 0.01
 *               instrument_no:
 *                 type: string
 *                 description: UTR/Cheque number
 *               instrument_date:
 *                 type: string
 *                 format: date
 *               bank_name:
 *                 type: string
 *               tds_applicable:
 *                 type: boolean
 *                 default: false
 *               tds_section:
 *                 type: string
 *                 enum: ["194C", "194J", "194Q"]
 *               tds_rate:
 *                 type: number
 *                 minimum: 0
 *                 maximum: 100
 *               allocations:
 *                 type: array
 *                 minItems: 1
 *                 items:
 *                   type: object
 *                   required:
 *                     - invoice_id
 *                     - allocated_amount
 *                   properties:
 *                     invoice_id:
 *                       type: string
 *                     allocated_amount:
 *                       type: number
 *                       minimum: 0.01
 *               remarks:
 *                 type: string
 *     responses:
 *       201:
 *         description: Payment receipt created and allocations posted
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 message:
 *                   type: string
 *                 data:
 *                   $ref: '#/components/schemas/PaymentReceipt'
 *       400:
 *         description: Validation error or allocation sum exceeds net received
 *       401:
 *         description: Unauthorized
 */
router.post('/payment-receipts', createPaymentReceipt);

/**
 * @swagger
 * /api/invoices/payment-receipts/{id}:
 *   get:
 *     summary: Get payment receipt details by ID
 *     tags: ["Phase 12 — Payment"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Payment Receipt ObjectId
 *     responses:
 *       200:
 *         description: Payment receipt with allocations and follow-ups
 *       404:
 *         description: Receipt not found
 */
router.get('/payment-receipts/:id', getPaymentReceiptById);

/**
 * @swagger
 * /api/invoices/payment-receipts/{id}/bounce:
 *   put:
 *     summary: Record cheque bounce and reverse all allocations
 *     tags: ["Phase 12 — Payment"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Payment Receipt ObjectId
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - bounce_reason
 *             properties:
 *               bounce_reason:
 *                 type: string
 *                 example: "Insufficient funds"
 *     responses:
 *       200:
 *         description: Cheque bounced — allocations reversed
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 message:
 *                   type: string
 *                 data:
 *                   type: object
 *                   properties:
 *                     receipt_no:
 *                       type: string
 *                     status:
 *                       type: string
 *                     allocations_reversed:
 *                       type: integer
 *       400:
 *         description: Not a cheque payment or already bounced
 *       404:
 *         description: Receipt not found
 */
router.put('/payment-receipts/:id/bounce', bouncePayment);

/**
 * @swagger
 * /api/invoices/payment-receipts/{id}/followup:
 *   put:
 *     summary: Log collection follow-up activity
 *     tags: ["Phase 12 — Collections"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Payment Receipt ObjectId
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - summary
 *             properties:
 *               channel:
 *                 type: string
 *                 enum: ["Call", "Email", "Visit", "WhatsApp"]
 *                 default: "Call"
 *               summary:
 *                 type: string
 *               promise_date:
 *                 type: string
 *                 format: date
 *               promise_amount:
 *                 type: number
 *     responses:
 *       200:
 *         description: Follow-up logged
 *       404:
 *         description: Receipt not found
 */
router.put('/payment-receipts/:id/followup', logCollectionFollowUp);

/**
 * @swagger
 * /api/invoices/ar-aging:
 *   get:
 *     summary: Accounts Receivable Aging Report
 *     tags: ["Phase 12 — Collections"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: as_of
 *         schema:
 *           type: string
 *           format: date
 *         description: Snapshot date (defaults to today)
 *     responses:
 *       200:
 *         description: AR aging by customer with buckets (0-30, 31-60, 61-90, 91-180, 180+)
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 data:
 *                   type: object
 *                   properties:
 *                     as_of:
 *                       type: string
 *                     customer_count:
 *                       type: integer
 *                     grand_totals:
 *                       type: object
 *                       properties:
 *                         current:
 *                           type: number
 *                         "0_30":
 *                           type: number
 *                         "31_60":
 *                           type: number
 *                         "61_90":
 *                           type: number
 *                         "91_180":
 *                           type: number
 *                         "180_plus":
 *                           type: number
 *                         total:
 *                           type: number
 *                     customers:
 *                       type: array
 */
router.get('/ar-aging', getArAging);

/**
 * @swagger
 * /api/invoices/credit-notes:
 *   post:
 *     summary: Create credit note against an invoice (returns/price corrections)
 *     tags: ["Phase 12 — Credit Note"]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - invoice_id
 *               - reason
 *               - items
 *             properties:
 *               invoice_id:
 *                 type: string
 *               reason:
 *                 type: string
 *                 enum: ["Sales Return", "Price Revision", "Quality Rejection", "Excess Billing", "Discount Adjustment", "Other"]
 *               reason_remarks:
 *                 type: string
 *               items:
 *                 type: array
 *                 minItems: 1
 *                 items:
 *                   type: object
 *                   required:
 *                     - part_no
 *                     - quantity
 *                     - unit_price
 *                   properties:
 *                     part_no:
 *                       type: string
 *                     part_name:
 *                       type: string
 *                     hsn_code:
 *                       type: string
 *                     unit:
 *                       type: string
 *                       default: "Nos"
 *                     quantity:
 *                       type: number
 *                       minimum: 0.001
 *                     unit_price:
 *                       type: number
 *                       minimum: 0
 *                     gst_percentage:
 *                       type: number
 *                       default: 18
 *     responses:
 *       201:
 *         description: Credit note issued and GL entry posted
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 message:
 *                   type: string
 *                 data:
 *                   $ref: '#/components/schemas/CreditNote'
 *       400:
 *         description: Validation error or invoice not found
 *       401:
 *         description: Unauthorized
 */
router.post('/credit-notes', createCreditNote);

/**
 * @swagger
 * /api/invoices/credit-notes:
 *   get:
 *     summary: List credit notes with filters
 *     tags: ["Phase 12 — Credit Note"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: customer_id
 *         schema:
 *           type: string
 *       - in: query
 *         name: invoice_id
 *         schema:
 *           type: string
 *       - in: query
 *         name: from
 *         schema:
 *           type: string
 *           format: date
 *       - in: query
 *         name: to
 *         schema:
 *           type: string
 *           format: date
 *       - in: query
 *         name: page
 *         schema:
 *           type: integer
 *           default: 1
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *           default: 20
 *     responses:
 *       200:
 *         description: Paginated credit note list
 */
router.get('/credit-notes', getCreditNotes);

/**
 * @swagger
 * /api/invoices/credit-notes/{id}:
 *   get:
 *     summary: Get credit note details by ID
 *     tags: ["Phase 12 — Credit Note"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Credit Note ObjectId
 *     responses:
 *       200:
 *         description: Credit note with items and GL posting status
 *       404:
 *         description: Credit note not found
 */
router.get('/credit-notes/:id', getCreditNoteById);

/**
 * @swagger
 * /api/invoices/gstr1-data:
 *   get:
 *     summary: Get GSTR-1 outward supply data for a period
 *     tags: ["Phase 12 — GST Compliance"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: month
 *         required: true
 *         schema:
 *           type: integer
 *           minimum: 1
 *           maximum: 12
 *         description: Month number (1-12)
 *       - in: query
 *         name: year
 *         required: true
 *         schema:
 *           type: integer
 *           minimum: 2020
 *           maximum: 2030
 *         description: Year (YYYY)
 *     responses:
 *       200:
 *         description: GSTR-1 data with B2B invoices, HSN summary, credit notes
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 data:
 *                   type: object
 *                   properties:
 *                     period:
 *                       type: object
 *                     gstin:
 *                       type: string
 *                     b2b:
 *                       type: array
 *                     totals:
 *                       type: object
 *       400:
 *         description: Month and year are required
 */
router.get('/gstr1-data', getGstr1Data);

/**
 * @swagger
 * /api/invoices/gstr3b-data:
 *   get:
 *     summary: Get GSTR-3B monthly summary
 *     tags: ["Phase 12 — GST Compliance"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: month
 *         required: true
 *         schema:
 *           type: integer
 *           minimum: 1
 *           maximum: 12
 *         description: Month number (1-12)
 *       - in: query
 *         name: year
 *         required: true
 *         schema:
 *           type: integer
 *           minimum: 2020
 *           maximum: 2030
 *         description: Year (YYYY)
 *     responses:
 *       200:
 *         description: GSTR-3B summary with output tax, ITC, net payable
 *       400:
 *         description: Month and year are required
 */
router.get('/gstr3b-data', getGstr3bData);

/**
 * @swagger
 * /api/invoices/reports/monthly-revenue:
 *   get:
 *     summary: Monthly revenue report by customer and product category
 *     tags: ["Phase 12 — Reports"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: month
 *         schema:
 *           type: integer
 *           minimum: 1
 *           maximum: 12
 *         description: Month number (defaults to current month)
 *       - in: query
 *         name: year
 *         schema:
 *           type: integer
 *           minimum: 2020
 *           maximum: 2030
 *         description: Year (defaults to current year)
 *     responses:
 *       200:
 *         description: Revenue summary with customer breakdown and 12-month trend
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 data:
 *                   type: object
 *                   properties:
 *                     period:
 *                       type: object
 *                     summary:
 *                       type: object
 *                       properties:
 *                         count:
 *                           type: integer
 *                         taxable:
 *                           type: number
 *                         gst:
 *                           type: number
 *                         grand:
 *                           type: number
 *                         outstanding:
 *                           type: number
 *                     by_customer:
 *                       type: array
 *                     trend_12m:
 *                       type: array
 */
router.get('/reports/monthly-revenue', getMonthlyRevenue);

/**
 * @swagger
 * /api/invoices/tds-reconciliation/{customer_id}/{year}:
 *   get:
 *     summary: TDS reconciliation report for a customer and financial year
 *     tags: ["Phase 12 — TDS"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: customer_id
 *         required: true
 *         schema:
 *           type: string
 *         description: Customer ObjectId
 *       - in: path
 *         name: year
 *         required: true
 *         schema:
 *           type: integer
 *           minimum: 2020
 *           maximum: 2030
 *         description: Financial year start year (e.g., 2025 for FY 2025-26)
 *     responses:
 *       200:
 *         description: TDS summary by section
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 data:
 *                   type: object
 *                   properties:
 *                     customer_id:
 *                       type: string
 *                     financial_year:
 *                       type: string
 *                     total_receipts:
 *                       type: integer
 *                     total_tds:
 *                       type: number
 *                     by_section:
 *                       type: array
 *                       items:
 *                         type: object
 *                         properties:
 *                           section:
 *                             type: string
 *                           receipts:
 *                             type: integer
 *                           total_tds:
 *                             type: number
 *       400:
 *         description: Invalid customer ID or year
 */
router.get('/tds-reconciliation/:customer_id/:year', getTdsReconciliation);

/**
 * @swagger
 * /api/invoices/sales-orders/{id}/close:
 *   put:
 *     summary: Close a Sales Order (fully delivered + fully paid)
 *     tags: ["Phase 12 — SO Closure"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Sales Order ObjectId
 *     responses:
 *       200:
 *         description: Sales Order closed successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 message:
 *                   type: string
 *                 data:
 *                   type: object
 *                   properties:
 *                     so_number:
 *                       type: string
 *                     status:
 *                       type: string
 *                     closed_at:
 *                       type: string
 *       400:
 *         description: Cannot close — not fully delivered or not fully paid
 *       404:
 *         description: Sales Order not found
 */
router.put('/sales-orders/:id/close', closeSalesOrder);

// ================================================================
// PARAMETERIZED ROUTES (WITH :id) - MUST COME LAST
// ================================================================

/**
 * @swagger
 * /api/invoices/{id}:
 *   get:
 *     summary: Get complete invoice details by ID
 *     tags: ["Phase 12 — Invoice"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Invoice ObjectId
 *     responses:
 *       200:
 *         description: Complete invoice with items, HSN breakup, payment history
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 data:
 *                   $ref: '#/components/schemas/Invoice'
 *       404:
 *         description: Invoice not found
 *       401:
 *         description: Unauthorized
 */
router.get('/:id', getInvoiceById);

/**
 * @swagger
 * /api/invoices/{id}/pdf-data:
 *   get:
 *     summary: Get invoice data for frontend PDF generation
 *     description: |
 *       Returns all necessary data for the frontend to generate a professional
 *       GST invoice PDF including:
 *       - Company letterhead details
 *       - Customer details
 *       - Line items with HSN, GST breakup
 *       - QR code data URL (if e-Invoice generated)
 *       - Pre-computed amount in words
 *       - Bank details
 *     tags: ["Phase 12 — Invoice"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Invoice ObjectId
 *     responses:
 *       200:
 *         description: JSON data ready for frontend PDF rendering
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 data:
 *                   type: object
 *                   properties:
 *                     invoice:
 *                       $ref: '#/components/schemas/Invoice'
 *                     company:
 *                       type: object
 *                     qr_code_data_url:
 *                       type: string
 *                       description: Base64 QR code image for e-Invoice
 *                     bank_details:
 *                       type: object
 *       404:
 *         description: Invoice not found
 */
router.get('/:id/pdf-data', getInvoiceDataForPdf);

/**
 * @swagger
 * /api/invoices/{id}/submit-irn:
 *   post:
 *     summary: Submit invoice to e-Invoice portal (IRP) for IRN generation
 *     tags: ["Phase 12 — e-Invoice"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Invoice ObjectId
 *     responses:
 *       200:
 *         description: IRN generated successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 message:
 *                   type: string
 *                 data:
 *                   type: object
 *                   properties:
 *                     invoice_no:
 *                       type: string
 *                     irn:
 *                       type: string
 *                     ack_no:
 *                       type: string
 *                     irn_generated_at:
 *                       type: string
 *                       format: date-time
 *                     irn_cancellable:
 *                       type: boolean
 *                     hours_since_irn:
 *                       type: number
 *       400:
 *         description: Cannot submit (status invalid or IRN already exists)
 *       502:
 *         description: IRP API error
 */
router.post('/:id/submit-irn', submitIRN);

/**
 * @swagger
 * /api/invoices/{id}/cancel-irn:
 *   delete:
 *     summary: Cancel e-Invoice IRN (within 24 hours only)
 *     tags: ["Phase 12 — e-Invoice"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Invoice ObjectId
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - cancel_reason
 *             properties:
 *               cancel_reason:
 *                 type: string
 *                 example: "Data entry mistake in customer GSTIN"
 *     responses:
 *       200:
 *         description: IRN cancelled successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 message:
 *                   type: string
 *                 data:
 *                   type: object
 *                   properties:
 *                     invoice_no:
 *                       type: string
 *                     irn:
 *                       type: string
 *                     irn_cancelled_at:
 *                       type: string
 *                       format: date-time
 *       400:
 *         description: Cannot cancel (beyond 24h or no IRN)
 *       401:
 *         description: Unauthorized
 */
router.delete('/:id/cancel-irn', cancelIRN);

/**
 * @swagger
 * /api/invoices/{id}/send:
 *   post:
 *     summary: Send invoice to customer email
 *     description: |
 *       Returns invoice data including email status.
 *       Frontend can generate PDF and send via email using the returned data.
 *       If SMTP is configured, email is sent automatically.
 *       Returns email_sent flag and invoice data.
 *     tags: ["Phase 12 — Invoice"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Invoice ObjectId
 *     requestBody:
 *       required: false
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               email:
 *                 type: string
 *                 format: email
 *                 description: Override recipient email (optional)
 *     responses:
 *       200:
 *         description: Invoice sent (or email queued)
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 message:
 *                   type: string
 *                 data:
 *                   type: object
 *                   properties:
 *                     invoice:
 *                       $ref: '#/components/schemas/Invoice'
 *                     email_sent:
 *                       type: boolean
 *                     sent_to:
 *                       type: string
 *                     qr_code_data_url:
 *                       type: string
 *       400:
 *         description: Cannot send cancelled invoice
 *       404:
 *         description: Invoice not found
 */
router.post('/:id/send', sendInvoice);
router.put('/:id/confirm', confirmInvoice);
router.put('/:id/cancel', cancelInvoice);

/**
 * @swagger
 * /api/invoices/{id}/apply-advance:
 *   put:
 *     summary: Apply customer advance balance to an invoice
 *     tags: ["Phase 12 — Payment"]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: Invoice ObjectId
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - advance_id
 *               - amount
 *             properties:
 *               advance_id:
 *                 type: string
 *                 description: CustomerAdvance ObjectId
 *               amount:
 *                 type: number
 *                 minimum: 0.01
 *     responses:
 *       200:
 *         description: Advance applied successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                 message:
 *                   type: string
 *                 data:
 *                   type: object
 *                   properties:
 *                     invoice_no:
 *                       type: string
 *                     advance_no:
 *                       type: string
 *                     applied_amount:
 *                       type: number
 *                     invoice_balance_due:
 *                       type: number
 *                     advance_balance:
 *                       type: number
 *       400:
 *         description: Invalid advance or insufficient balance
 *       404:
 *         description: Invoice or advance not found
 */
router.put('/:id/apply-advance', applyAdvanceToInvoice);

module.exports = router;

// ─────────────────────────────────────────────────────────────────────────────
// SWAGGER COMPONENT DEFINITIONS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @swagger
 * components:
 *   schemas:
 *     Invoice:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *         invoice_no:
 *           type: string
 *           example: "INV-202503-0001"
 *         invoice_date:
 *           type: string
 *           format: date
 *         invoice_type:
 *           type: string
 *         so_id:
 *           type: string
 *         so_number:
 *           type: string
 *         dc_ids:
 *           type: array
 *           items:
 *             type: string
 *         dc_numbers:
 *           type: array
 *           items:
 *             type: string
 *         company_name:
 *           type: string
 *         company_gstin:
 *           type: string
 *         customer_id:
 *           type: string
 *         customer_name:
 *           type: string
 *         customer_gstin:
 *           type: string
 *         gst_type:
 *           type: string
 *           enum: ["CGST/SGST", "IGST"]
 *         items:
 *           type: array
 *           items:
 *             type: object
 *             properties:
 *               part_no:
 *                 type: string
 *               part_name:
 *                 type: string
 *               hsn_code:
 *                 type: string
 *               dispatched_qty:
 *                 type: number
 *               unit_price:
 *                 type: number
 *               taxable_amount:
 *                 type: number
 *               gst_percentage:
 *                 type: number
 *               cgst_amount:
 *                 type: number
 *               sgst_amount:
 *                 type: number
 *               igst_amount:
 *                 type: number
 *               total_amount:
 *                 type: number
 *         hsn_breakup:
 *           type: array
 *           items:
 *             type: object
 *             properties:
 *               hsn_code:
 *                 type: string
 *               taxable_value:
 *                 type: number
 *               gst_percentage:
 *                 type: number
 *               cgst_amount:
 *                 type: number
 *               sgst_amount:
 *                 type: number
 *               igst_amount:
 *                 type: number
 *               total_tax:
 *                 type: number
 *         taxable_total:
 *           type: number
 *         cgst_total:
 *           type: number
 *         sgst_total:
 *           type: number
 *         igst_total:
 *           type: number
 *         gst_total:
 *           type: number
 *         grand_total:
 *           type: number
 *         balance_due:
 *           type: number
 *         amount_in_words:
 *           type: string
 *         payment_status:
 *           type: string
 *           enum: ["Unpaid", "Partially Paid", "Fully Paid"]
 *         due_date:
 *           type: string
 *           format: date
 *         irn:
 *           type: string
 *         irn_generated_at:
 *           type: string
 *           format: date-time
 *         irn_cancellable:
 *           type: boolean
 *         hours_since_irn:
 *           type: number
 *         status:
 *           type: string
 *         sent_at:
 *           type: string
 *           format: date-time
 *         sent_to:
 *           type: string
 *
 *     InvoiceSummary:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *         invoice_no:
 *           type: string
 *         invoice_date:
 *           type: string
 *         customer_name:
 *           type: string
 *         grand_total:
 *           type: number
 *         balance_due:
 *           type: number
 *         payment_status:
 *           type: string
 *         status:
 *           type: string
 *         due_date:
 *           type: string
 *         is_overdue:
 *           type: boolean
 *
 *     PaymentReceipt:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *         receipt_no:
 *           type: string
 *         receipt_date:
 *           type: string
 *         customer_id:
 *           type: string
 *         customer_name:
 *           type: string
 *         payment_mode:
 *           type: string
 *         total_amount:
 *           type: number
 *         tds_applicable:
 *           type: boolean
 *         tds_section:
 *           type: string
 *         tds_rate:
 *           type: number
 *         tds_amount:
 *           type: number
 *         net_received:
 *           type: number
 *         allocations:
 *           type: array
 *           items:
 *             type: object
 *             properties:
 *               invoice_id:
 *                 type: string
 *               invoice_no:
 *                 type: string
 *               allocated_amount:
 *                 type: number
 *         status:
 *           type: string
 *         follow_ups:
 *           type: array
 *
 *     CustomerAdvance:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *         advance_no:
 *           type: string
 *         advance_date:
 *           type: string
 *         customer_id:
 *           type: string
 *         customer_name:
 *           type: string
 *         payment_mode:
 *           type: string
 *         total_amount:
 *           type: number
 *         balance:
 *           type: number
 *         adjustments:
 *           type: array
 *         status:
 *           type: string
 *
 *     CreditNote:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *         cn_no:
 *           type: string
 *         cn_date:
 *           type: string
 *         invoice_id:
 *           type: string
 *         invoice_no:
 *           type: string
 *         customer_id:
 *           type: string
 *         customer_name:
 *           type: string
 *         reason:
 *           type: string
 *         items:
 *           type: array
 *         taxable_total:
 *           type: number
 *         cgst_total:
 *           type: number
 *         sgst_total:
 *           type: number
 *         igst_total:
 *           type: number
 *         grand_total:
 *           type: number
 *         status:
 *           type: string
 */